dependencies:
  - name: <app-chart-name>
    version: 1.0.0-<build tag version>
    repository: http://artifactory.garage-devtools-sfo-rhos.us-east.containers.appdomain.cloud/generic-local/garage-devtools-sfo/
